version: '3.8'
services:
  app:
    image: springboot-app:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=mohamad.sadem@gmail.com
      - SPRING_MAIL_PASSWORD=befuxrzzhgovdump
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
