services:
  db:
    image: mysql:8
    container_name: shopishop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root123@
      MYSQL_DATABASE: ShopiShop
      MYSQL_USER: root
      MYSQL_PASSWORD: Root123@
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shopishop-network

  app:
    image: shopishop-app
    container_name: shopishop-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ShopiShop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root123@
    networks:
      - shopishop-network

volumes:
  db_data:

networks:
  shopishop-network:
    driver: bridge
